apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: testing-from-configmap-yaml-key-course
          valueFrom:
            configMapKeyRef:
              name: config-test
              key: course
        - name: testing-from-configmap-yaml-key-practice
          valueFrom:
            configMapKeyRef:
              name: config-test
              key: practice