---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
labels:
  {
    name: service-web-nginx
  }
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name:service-web-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---